version: '3.9'
services:
  db:
    image: mysql:8.0
    container_name: crm_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: crm_immobilier
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=caching_sha2_password

  phpmyadmin:
    image: phpmyadmin:5
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db

volumes:
  db_data:
